receivers:
  otlp:
    protocols:
      grpc:
      http:
  hostmetrics:
    collection_interval: 1m
    root_path: /hostfs
    scrapers:
      cpu:
      load:
      memory:
      disk:
      filesystem:
      network:
      paging:
      processes:

processors:
  batch:

exporters:
  logging:
  otlp:
    endpoint: otlp.telemetryhub.com:4317
    headers:
      "X-TELEMETRYHUB-KEY": "your-telemetryhub-key"

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [otlp, logging]
